config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
             },
             controllers: {
               sessions: 'admin/sessions',
               registrations: 'admin/registrations'
             }
  resources :selling_orders, only: [:update]
  resources :customers
  resources :balances
  resources :expenses
  resources :inventory_purchases
  resources :providers
  resources :products
  resources :homepages, only: [:index]
  resources :categories
  namespace :super_admin do
    resources :balances
    resources :admins
  end

  authenticated :admin, ->(admin) { admin.super_admin? } do
    root "super_admin/balances#index"
  end
  root "products#index", as: :admin_root
end

app/models/selling_order.rb
class SellingOrder < ApplicationRecord
  belongs_to :inventory_purchase
  belongs_to :customer
  belongs_to :balance
  has_one :product, through: :inventory_purchase
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  after_create :reduce_existences
  before_update :check_last_balance
  after_update_commit :update_balance
  before_create :round_nums

  def debt_payed
    (quantity * price).round(2)
  end

  def update_date
    updated_at.strftime("%b %d")
  end

  def check_last_balance
    if Balance.last_created_month_day > balance.created_month
      self.balance = Balance.last_created
    end
  end

  def update_balance

    new_balance = balance.sub_total + (quantity * price).round(2)
    balance.update_attribute(:sub_total, new_balance )
  end

  def reduce_existences
    inventory_purchase.decrement!(:stock_quantity, self.quantity)
    inventory_purchase.update(sold_out: true) if zero_stock?
  end

  def zero_stock?
    inventory_purchase.stock_quantity.zero?
  end
  def round_nums
    self.price = self.price.round(2)
  end
end

app/controllers/selling_orders_controller.rb
class SellingOrdersController < ApplicationController
  before_action :set_selling_order, only: [:update]
  def update
    if @selling_order.update(selling_order_params)
      streams = []
      streams << turbo_stream.replace('customer_total_debt', partial: 'customers/customer_total_debt', locals: { customer: @selling_order.customer})
      streams << turbo_stream.remove("selling_order_#{@selling_order.id}")
      streams << turbo_stream.append('paid_selling_orders', partial: 'selling_orders/selling_order', locals: { selling_order: @selling_order })
      render turbo_stream: streams
    else
      turbo_error_message(@selling_order)
    end
  end

  private

  def set_selling_order
    @selling_order = SellingOrder.find(params[:id])
  end

  def selling_order_params
    params.require(:selling_order).permit(:paid)
  end

end

app/helpers/selling_orders_helper.rb
module SellingOrdersHelper
  def paid_update_button(selling_order)
    return if selling_order.paid

    button_to 'Paid', selling_order_path({id: selling_order.id, paid: true}), method: :put, class: pink_btn
  end

  def payment_status(selling_order)
    css = 'card user_order'
    return css if selling_order.paid

    css.then { |text| text += ' with_stock'}
  end

    def order_button_if_stock_left(inventory_purchase)
      return unless inventory_purchase.stock_left?

      content_tag(:button, "Orden", class: "btn btn-primary", "data-action": "nested-form#add", type: "button")
    end

  def display_sizes(inventory_purchase)
    return unless inventory_purchase.size

    content_tag(:div, class: "form-group mb-2") do
      content_tag(:div, "talla: #{inventory_purchase.size}")
    end

  end

  def display_colors(inventory_purchase)
    return if inventory_purchase.colors.empty?

    content_tag(:div, class: "form-group mb-2") do
      content_tag(:p, "colores: #{inventory_purchase.colors.to_sentence}")
    end

  end

end

app/views/selling_orders/_card.html.erb
<div id="<%= dom_id selling_order %>"  >
  <div class="<%= payment_status(selling_order) %>" >
    <div class="card-body p-1">
      <p class="m-0"><%= link_to selling_order.customer.name, customer_path(selling_order.customer.id), class: 'text-decoration-none' %>
      <p class="m-0">cant: <%= selling_order.quantity %></p>
    </div>
  </div>
</div>

app/views/selling_orders/_form.erb
<div id="selling_order" class="nested-form-wrapper form-inline" data-new-record="<%= f.object.new_record? %>" data-controller="special-price">
  <div class="card p-2" >
    <div class="mb-2">
      <%= f.label :descuento %>
      <%= f.check_box :discount, checked: f.object.discount, data: {
        action: 'click->special-price#toggle'
      } %>
    </div>
    <%= price_field(f, f_parent) %>

    <div class="form-group mb-2">
      <%= f.label :customer_id %>
      <%= f.collection_select :customer_id, Customer.all, :id, :full_name, {}, {class: 'form-select'} %>
    </div>

    <div class="mb-2">
      <%= f.label :quantity %>
      <%= f.select :quantity, (1..f_parent.object.stock_quantity).to_a, {}, class: 'form-select' %>
    </div>



    <%= f.hidden_field :balance_id, value: f_parent.object.last_balance_id  %>

    <%= f.hidden_field :_destroy %>
    <button type="button" data-action="nested-form#remove" class="btn btn-danger mb-1">Cancelar</button>
    <%= f_parent.submit 'Save', class: pink_btn %>
  </div>
</div>

app/views/selling_orders/_selling_order.html.erb
<div class="card d-inline-block p-2">
  <div class="form-group mb-2">
    <%= selling_order.inventory_purchase.product.name %>
  </div>

  <div class="form-group mb-2">
    cantidad: <%= selling_order.quantity %>
  </div>
  <div class="form-group mb-2">
    precio: <%= selling_order.inventory_purchase.selling_price %>
  </div>

  <div class="form-group mb-2">
    <%= format_date(selling_order.created_at) %>
  </div>
</div>

app/views/selling_orders/_simple_form.html.erb
<div class="card d-inline-block p-2" id="<%= dom_id selling_order %>">
  <%= form_with model: selling_order do |f| %>

    <div class="form-group mb-2">
      <%= selling_order.inventory_purchase.product.name %>
    </div>

    <div class="form-group mb-2">
      deuda: <%= selling_order.debt_payed %>
    </div>

    <%= display_sizes(selling_order.inventory_purchase) %>
    <%= display_colors(selling_order.inventory_purchase) %>

    <div class="form-group mb-2">
      <%= format_date(selling_order.created_at) %>
    </div>
    <%= f.hidden_field :paid, value: true %>

    <%= f.submit 'Pagar', class: pink_btn %>
  <% end %>
</div>