config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
             },
             controllers: {
               sessions: 'admin/sessions',
               registrations: 'admin/registrations'
             }
  resources :selling_orders, only: [:update]
  resources :customers
  resources :balances
  resources :expenses
  resources :inventory_purchases
  resources :providers
  resources :products
  resources :homepages, only: [:index]
  resources :categories
  namespace :super_admin do
    resources :balances
    resources :admins
  end

  authenticated :admin, ->(admin) { admin.super_admin? } do
    root "super_admin/balances#index"
  end
  root "products#index", as: :admin_root
end

app/views/shared/_admin_links.html.erb
<ul class="navbar-nav align-items-center">
  <li class="nav-item">
    <%= link_to 'Proveedores', providers_path, class: active_nav?(providers_path) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Categorias', categories_path, class: active_nav?(categories_path) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Productos', products_path, class: active_nav?(products_path) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Clientes', customers_path, class: active_nav?(customers_path) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Balances', balances_path, class: active_nav?(balances_path) %>
  </li>
</ul>

app/views/shared/_customers_filter.html.erb
<div class="px-4">
  <button class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Filtro
  </button>
  <ul class="dropdown-menu">
    <%= link_to "Fecha", { sort_by_name: "created_at" }, class: "dropdown-item" %>
    <%= link_to "Nombre", { sort_by_name: "name" }, class: "dropdown-item"  %>
    <%= link_to "Pagadores", { paid_orders: "" }, class: "dropdown-item" %>
    <%= link_to "Deudores", { unpaid_orders: "" }, class: "dropdown-item"  %>
  </ul>
</div>

app/views/shared/_error_message.html.erb
<%= turbo_frame_tag 'error_message' do %>
  <div data-controller="error-message" class="error__message">
      <div class="px-2">
          <%= message %>
      </div>
    <%= link_to 'X','', data: {
      controller: 'error-message',
      action: 'error-message#close_error_message'
    }, class: 'px-3' %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <div class="nav-item mobile_log_out">
        <%= button_to destroy_admin_session_path, method: :delete, class: red_btn do %>
          <i class="fa-solid fa-right-from-bracket"></i>
        <% end %>
      </div>
      <%= show_filter(params) %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <%= admins_nav_links(current_admin) %>
    </div>
    <div class="nav-item desktop_log_out">
      <%= button_to destroy_admin_session_path, method: :delete, class: red_btn do %>
        <i class="fa-solid fa-right-from-bracket"></i>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_products_filter.html.erb
<div class="px-4 filter">
  <button class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Filtro
  </button>
  <ul class="dropdown-menu">
    <%= link_to "Fecha", { sort_by_name: "created_at" }, class: "dropdown-item" %>
    <%= link_to "Nombre", { sort_by_name: "name" }, class: "dropdown-item"%>
  </ul>
</div>

app/views/shared/_super_admin_link.html.erb
<ul class="navbar-nav align-items-center">
  <li class="nav-item">
    <%= link_to 'Balances', super_admin_balances_path, class: active_nav?(super_admin_balances_path) %>
  </li>
  <li class="nav-item">
    <%= link_to 'Admin', super_admin_admins_path, class: active_nav?(super_admin_admins_path) %>
  </li>
</ul>