config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
             },
             controllers: {
               sessions: 'admin/sessions',
               registrations: 'admin/registrations'
             }
  resources :selling_orders, only: [:update]
  resources :customers
  resources :balances
  resources :expenses
  resources :inventory_purchases
  resources :providers
  resources :products
  resources :homepages, only: [:index]
  resources :categories
  namespace :super_admin do
    resources :balances
    resources :admins
  end

  authenticated :admin, ->(admin) { admin.super_admin? } do
    root "super_admin/balances#index"
  end
  root "products#index", as: :admin_root
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  before_save :name_to_downcase
  has_many :product_categories
  has_many :products, through: :product_categories
  scope :ordered_by_name, -> { order(name: :asc) }
  def name_to_downcase
    self.name = self.name.downcase
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:edit, :update]
  def index
    @category = Category.new
    @categories = Category.ordered_by_name
  end

  def edit;end

  def update
    if @category.update(categories_params)
      render turbo_stream: turbo_stream.replace("category_#{@category.id}", partial: 'categories/category', locals: { category: @category })
    else
      turbo_error_message(@category)
    end
  end

  def create
    @category = Category.new(categories_params)

    if @category.save
      streams = []
      streams << turbo_stream.append('categories', partial: 'categories/category', locals: { category: @category })
      streams << turbo_stream.replace('category_form', partial: 'categories/form', locals: { category: Category.new })
      render turbo_stream: streams
    else
      turbo_error_message(@category)
    end

  end



  def set_category
    @category = Category.find(params[:id])
  end

  def categories_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" >
  <div class="card p-2">
  <%= turbo_frame_tag "cat_edit_#{category.id}" do %>
    <%= category.name %>
    <%= link_to edit_category_path(category.id), class: 'grey_link' do %>
        <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, id: "category_form",
              data: {
                form_target: 'dropdownContent'
              }, class: invisible(category) do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: form_label %>
    <%= f.text_field :name, class: form_control %>
  </div>

  <div class="div">
    <%= f.submit 'Guardar', class: blue_btn %>
    <%= link_to 'back', categories_path, class: 'text-decoration-none' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= turbo_frame_tag "cat_edit_#{@category.id}" do %>
  <%= render 'form', category: @category %>
<% end %>

app/views/categories/index.html.erb
<%= model_template(@category, @categories) %>