config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
             },
             controllers: {
               sessions: 'admin/sessions',
               registrations: 'admin/registrations'
             }
  resources :selling_orders, only: [:update]
  resources :customers
  resources :balances
  resources :expenses
  resources :inventory_purchases
  resources :providers
  resources :products
  resources :homepages, only: [:index]
  resources :categories
  namespace :super_admin do
    resources :balances
    resources :admins
  end

  authenticated :admin, ->(admin) { admin.super_admin? } do
    root "super_admin/balances#index"
  end
  root "products#index", as: :admin_root
end

app/models/product.rb
class Product < ApplicationRecord
  include Filterable
  mount_uploader :image_data, ImageUploader
  belongs_to :provider
  has_many :inventory_purchases, -> { order(sold_out: :asc, created_at: :asc) }, dependent: :delete_all
  has_many :product_categories
  has_many :categories, through: :product_categories
  accepts_nested_attributes_for :inventory_purchases, allow_destroy: true
  accepts_nested_attributes_for :product_categories, allow_destroy: true
  validates_presence_of :name
  scope :filter_sort_by_name, ->(value) { order("#{value} ASC") }
  scope :filter_search, ->(value) { where( "name ILIKE :search OR description ILIKE :search", search: "%#{value.downcase}%") }
  scope :filter_categories, ->(value) { joins(:categories).where(categories: { id: value }).distinct }
  scope :products_cat, -> { Category.joins(:products).distinct.pluck(:id, :name)  }

  def tag_list_empty
    return unless tag_list.blank?

    errors.add(:tag_list, 'Categories cannot be empty')
  end

  def all_categories
    Category.all
  end

  def out_of_stock?
    inventory_purchases.where(sold_out: false).blank?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :selected_params, only: [:index]
  before_action :set_product, only: [:edit, :update, :show, :new]


  def index
    @product = Product.new
    @product.inventory_purchases.build
    @products = Product.filter(@selected_params).includes([:categories])

  end

  def new
    @inventory_purchase = @product.inventory_purchases.build
  end

  def show
    @inventory_purchases = @product.inventory_purchases
  end

  def edit;end

  def update
    if @product.update(products_params.merge(product_categories_params(params, true)))
      render turbo_stream: turbo_stream.replace("product_#{@product.id}", partial: 'products/simple_product', locals: { product: @product })
    else
      turbo_error_message(@product)
    end
  end

  def create
    @product = Product.new(products_params.merge(product_categories_params(params)))
    if @product.save
      create_new_product
      streams = []
      streams << turbo_stream.replace('product_form', partial: 'products/form', locals: { product: @new_product })
      streams << turbo_stream.prepend('products', partial: 'products/product', locals: { product: @product })
      render turbo_stream: streams
    else
      turbo_error_message(@product)
    end
  end

  private

  def create_new_product
    @new_product =  Product.new
    @new_product.inventory_purchases.build
  end

  def product_categories_params(params, update = false)
    category_ids = params[:product][:product_categories_attributes].reject(&:blank?)
    category_ids = category_ids - @product.category_ids if update
    product_categories_params = category_ids.map { |id| { category_id: id } }
    { product_categories_attributes: product_categories_params }
  end

  def set_product
    @product = Product.find(params[:id])#&.includes([:customer])
  end

  def products_params
    params.require(:product).permit(:name, :description, :provider_id, :faulty, :image_data,
                                    inventory_purchases_attributes: [:purchase_price, :stock_quantity, :selling_price],
                                    product_categories_attributes: [:category_id]
                                    )

  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def nested_inventory_purchases(product, f)
    return if product.persisted?

    render 'inventory_purchases/form', f: f
  end

    def product_categories_select(product, f)
      options = { multiple: true, class: 'form-select', id: 'validationTagsThreshold', data: { controller: 'tag-select', allow_clear: true, suggestions_threshold: 0 } }
      select = { include_blank: true }

      select[:selected] = product.category_ids if product.persisted?
      f.collection_select(:product_categories_attributes, product.all_categories, :id, :name, select, options)

    end

  def faulty_checkbox(f, product)
    return unless product.persisted?

    content_tag :div, class: 'mb-3' do
      concat f.label :faulty, class: 'mx-3'
      concat f.check_box :faulty, { checked: product.faulty }
    end
  end

  def faulty_prod_card(product)
    css = 'card'
    css += ' border-danger border-3' if product.faulty
    css += ' with_stock' unless product.out_of_stock?
    css
  end

  def product_form(product)
    product.persisted? ? '': 'd-none'
  end

  def render_image(product)
    if product.image_data.present?
      cl_image_tag(product.image_data.filename, width: 400, height: 400, crop: :fill, class: 'img-fluid')
    else
      image_tag('no_image.jpg',class: 'img-fluid')
    end
  end

end

app/views/products/_filters.html.erb
<%= form_tag(products_path, method: :get, class: 'd-flex flex-wrap') do %>
  <div class="d-flex bg-transparent">
    <%= submit_tag("Buscar", class: search_btn, method: :get) %>

    <%= select_tag :categories, options_from_collection_for_select(category_list, :first, :last),
                 { include_blank: 'Select a category', class: 'cat__select', multiple: true,
                   id: 'validationTagsThreshold', data: { controller: 'tag-select', allow_clear: true, suggestions_threshold: 0 }
                 } %>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_with(
      model: product, id: 'product_form',
      multipart: true,
      data: {
        form_target: 'dropdownContent',
}, class: invisible(product)) do |f| %>
  <div class="mb-3">
    <%= f.label :nombre, class: form_label %>
    <%= f.text_field :name, class: form_control %>
  </div>

  <div class="mb-3">
    <%= f.label :descripcion, class: form_label %>
    <%= f.text_area :description, class: form_control %>
  </div>

  <div class="mb-3">
    <%= f.label :selecciona_categoria %>
    <%= product_categories_select(product, f) %>
  </div>

  <div class="mb-3">
    <%= f.label :selecciona_proveedor %>
    <%= f.select :provider_id, options_for_select(current_admin.providers_select, selected: product.provider_id), { include_blank: false }, { class: 'form-select' } %>
  </div>

  <div class="mb-3">
    <%= f.label :image_data %>
    <%= f.file_field :image_data, class: form_control %>
  </div>

  <%#= nested_inventory_purchases(product, f) %>
  <%= faulty_checkbox(f, product) %>
  <%= f.submit 'Guardar', class: blue_btn %>
  <%= link_to 'Cancelar', product_path(product.id), class: 'text-decoration-none' if product.persisted? %>
<% end %>

app/views/products/_form_selling_orders.html.erb
<%= form_with model: inventory_purchase, html: { class: 'mx-2' }, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
  <div>
    <%= order_button_if_stock_left(inventory_purchase) %>
  </div>
  <div>
    <template data-nested-form-target="template">
      <%= f.fields_for :selling_orders, SellingOrder.new, child_index: 'NEW_RECORD' do |selling_fields| %>
        <%= render "selling_orders/form", f: selling_fields, f_parent: f %>
      <% end %>
    </template>
    <div data-nested-form-target="target"></div>
  </div>
<% end %>
<div class="selling_order_container" id="<%= dom_id inventory_purchase, "selling" %>">
  <% inventory_purchase.selling_orders.includes([:customer]).each do |selling_order| %>
    <%= render "selling_orders/card", selling_order: selling_order %>
  <% end %>
</div>

app/views/products/_new_purchase.html.erb
<div id="new_purchase" class="mt-3">
  <%= turbo_frame_tag 'new_inventory_purchase' do %>
    <%= link_to 'Agregar Compra', new_product_path({id: product.id}), class: pink_btn %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="card__container p-2">
  <%= link_to product_path(product.id), class: 'text-decoration-none' do %>
    <div class="<%= faulty_prod_card(product) %> p-2" id="<%= dom_id product %>" >
      <div class="card-body p-1">
        <h5 class="card-title">
          <strong>
            <%= product.name %>
          </strong>
        </h5>
      </div>
      <div class="card-body p-1">
        <p class="card-text"><%= product.description %></p>
        <%= product_form(product) %>
        <div class="image-wrapper">
          <%= render_image(product) %>
        </div>
      </div>
      <div class="card-body p-1 mt-1 d-flex flex-wrap justify-content-center">
        <% product.categories.each do |category| %>
          <span class="badge p-2"><%= category.name %></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_simple_product.html.erb
<div id="<%= dom_id product %>" >
  <div class="card-body p-0">
    <%= turbo_frame_tag "edit_product_#{product.id}" do %>
      <div class="card-body">
        <h5 class="card-title"><%= product.name %>
        <%= link_to edit_product_path(product.id), class: 'grey_link' do %>
            <i class="fa-solid fa-pen-to-square"></i>
          </h5>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<%= turbo_frame_tag "edit_product_#{@product.id}" do %>
  <%= render 'form', product: @product %>
<% end %>

app/views/products/index.html.erb
<%= model_template(@product, @products, true) %>

app/views/products/new.html.erb
<%= turbo_frame_tag 'new_inventory_purchase' do %>
  <%= render 'inventory_purchases/simple_form', inventory_purchase: @inventory_purchase %>
<% end %>

app/views/products/show.html.erb
<div class="p-2">
  <%= render 'simple_product', product: @product %>
  <%= render 'products/new_purchase', product: @product %>
  <div class="mt-4" id="inventory_purchases">
    <%= render @inventory_purchases %>
  </div>
</div>